os: osx
osx_image: xcode8.2
sudo: false
language: python
	python:
		- 3.5.1
services:
		- mysql
		- nginx
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- brew update
- mysql -e 'CREATE DATABASE IF NOT EXISTS edc character set utf8;'
install:
- sudo easy_install pip
- pip install --upgrade pip
- pip install -r requirements.txt
branches:
	only: 
		- develop
