os: osx
osx_image: xcode8.2
sudo: required
language: generic
services:
- mysql
- nginx
before_install:
- export DISPLAY=:99.0
- brew update
- brew install python3
- mysql -e 'CREATE DATABASE IF NOT EXISTS edc character set utf8;'
install:
- sudo easy_install pip
- pip install --upgrade pip
- pip install -r requirements.txt
branches:
 only: 
 - develop
